steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-cloud-build-repo/gcp-cloud-build-nodejs:$COMMIT_SHA', '.']

  # Step 2: Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-cloud-build-repo/gcp-cloud-build-nodejs:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gcp-cloud-build-nodejs',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-cloud-build-repo/gcp-cloud-build-nodejs:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
